name: ocs-advanced-binder
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel
  - xarray=2024.10
  - zarr=2.18
  - rioxarray=0.17
  - geopandas=1.0
  - shapely=2.0
  - numpy=2.0
  - pandas=2.2
  - matplotlib=3.9
  - holoviews=1.19
  - cartopy=0.24
  - hvplot=0.11
  - scikit-learn=1.5
  - xgboost=2.1
  - s3fs=2024.10
  - dask=2024.10
  - xvec=0.3
  - pystac-client=0.8
  - stackstac=0.5
  - fsspec=2024.10
  - metpy
  - boto3
  - pip
  - pip:
    - lexcube
